/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './App.tsx'],
  theme: {
    extend: {
      colors: {
        mira: {
          primary: '#c96442',
          'primary-dark': '#a95034',
          success: '#22c55e',
          warning: '#f59e0b',
          danger: '#ef4444',
          'danger-light': '#fca5a5',
          muted: '#87867f',
          'bg-base': '#f5f4ed',
          'bg-subtle': '#e8e6dc',
          'bg-input': '#faf9f5',
          'bg-bubble': '#e8e6dc',
          'text-base': '#141413',
          'text-secondary': '#3d3d3a',
          'text-tertiary': '#5e5d59',
          'text-muted': '#87867f',
          'text-placeholder': '#87867f',
          border: '#e8e6dc',
          'border-light': '#f0eee6',
          hint: '#e8e6dc',
          'hint-text': '#a95034',
          banner: '#e8e6dc',
          'banner-text': '#5e5d59',
        },
      },
      borderRadius: {
        'mira-sm': '8px',
        'mira-md': '12px',
        'mira-lg': '16px',
        'mira-xl': '20px',
        'mira-full': '9999px',
      },
      fontSize: {
        'mira-xs': ['12px', { lineHeight: '16px' }],
        'mira-sm': ['13px', { lineHeight: '20px' }],
        'mira-base': ['14px', { lineHeight: '22px' }],
        'mira-md': ['15px', { lineHeight: '22px' }],
        'mira-lg': ['16px', { lineHeight: '24px' }],
        'mira-xl': ['17px', { lineHeight: '24px' }],
        'mira-2xl': ['18px', { lineHeight: '28px' }],
        'mira-3xl': ['20px', { lineHeight: '28px' }],
        'mira-4xl': ['28px', { lineHeight: '36px' }],
      },
      spacing: {
        'mira-xs': '4px',
        'mira-sm': '8px',
        'mira-md': '12px',
        'mira-lg': '16px',
        'mira-xl': '24px',
        'mira-section': '32px',
      },
    },
  },
  plugins: [],
};
